# 站点名称
title = "Cecilia's blog"
# 站点 URL
baseURL = "http://localhost:1313/"
# 使用 themes/ 中的哪个主题, 注意大小写
theme = "Mainroad-master"

# 中文显示配置
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
enableEmoji = true
hasCJKLanguage = true

# 每页显示多少条博文标题
paginate = "10"

# hugo 发布设置, 发布生成的文件夹路径
publishDir = "/d/blog/myblog/publish"
# 是否清理发布文件夹中多余的文件
cleanDestinationDir = true

[[module.imports]]
path = "github.com/Cecilia404404/Mainroad-master"

# 页面底部的作者信息
[Author]
    name = "Cecilia"
    bio = "Humo sum, humani nihil ame alienum puton."
    avatar = "/res/avatar.png"  # logo

[Params]
    # 站点描述
    description = "Cecilia's blog"
    # 版权声明
    copyright = "版权所有"
    twitter_cards = false
    # 使用 继续阅读 功能
    readmore = true
    # 文章底部显示作者信息
    authorbox = true
    # 显示文章目录
    toc = true
    # 显示 上一篇/下一篇博文
    pager = true
    # 博文元数据显示配置
    post_meta = ["author", "date", "categories", "translations"]
    # 主页中显示哪些
    mainSections = ["posts",]
    # 如果觉得 Google 字体导致网站打开太慢, 可以用其它的替代 API
    googleFontsLink = "/res/font/opensans/opensans.css"
    # 自定义 CSS 和 JS
    customCSS = ["/res/css/custom.css"]
    customJS = ["/res/js/custom.js"]

[Params.Logo]
    subtitle = "In libris libertas."
    # 此处可以添加网站 Logo, 显示在页面顶部

[Params.style.vars]
    # 页面高亮 (链接等) 颜色（海绿色）
    highlightColor = "#2E8B57"

# 使用侧边栏, 可接受: 'left', false, true
[Params.sidebar]
    home = true
    list = true
    single = true
    widgets = ["search", "recent", "categories", "taglist", "social", "languages", "sidemenu"]

[Params.widgets]
    recent_num = 10 # Set the number of articles in the "Recent articles" widget
    categories_counter = true # Enable counter for each category in "Categories" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
    email = "springcecily@gmail.com"

# 在顶部添加菜单栏, weight 决定显示顺序
[menu]
    [[menu.main]]
        identifier = "posts"
        name = "所有文章"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "categories"
        name = "合集"
        url = "/categories/"
        weight = 20
    [[menu.main]]
        identifier = "资料整理1"
        name = "档案馆"
        url = "/post/"
        weight = 20
    [[menu.main]]
        identifier = "资料整理2"
        name = "记录"
        url = "/docs/"
        weight = 20
    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 30
    [[menu.main]]
        identifier = "photos"
        name = "postcards相册"
        url = "/photos/"
        weight = 40
    [[menu.main]]
        identifier = "about"
        name = "关于我"
        url = "/about/"
        weight = 40
