baseURL = "https://springcecilia.blog"
languageCode = 'zh-cn'
title = 'Cecilia的博客'
theme = "hugo-theme-stack"
summaryLength = 20
paginate = 10
disqusShortname = ''
# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
enableEmoji = true
disablePathToLower = true
timeZone = "Asia/Shanghai"

[permalinks]
post = "/:filename/"
page = "/:slug/"

[params]
mainSections = 'post'
featuredImageField = "image"
rssFullContent = true
enableimgloop = true 
favicon = "img/favicon.png"

  [params.dateFormat]
  published = "2006-01-02"
  lastUpdated = "2006-01-02"
  
  [params.sidebar]
  compact = false
  emoji = ""
  subtitle = "In libris libertas."
  
    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"
    
  [params.article]
  math = false
  toc = true
  enableimgloop = true 
  readingTime = true
  
    [params.article.license]
    enabled = true
    default = "Licensed under CC BY springceceilia"
  
  [[params.widgets.homepage]]
  type = "search"
  

  [[params.widgets.homepage]]
  type = "archives"
  
    [params.widgets.homepage.params]
    limit = 10
 

  [[params.widgets.homepage]]
  type = "tag-cloud"
  
    [params.widgets.homepage.params]
    limit = 12
  
  [[params.widgets.page]]
  type = "toc"

  [params.opengraph.twitter]
  site = ""
  card = "summary_large_image"
  
  [params.defaultImage.opengraph]
  enabled = false
  local = false
  src = ""
  
  [params.colorScheme]
  toggle = true
  default = "auto"

  [params.imageProcessing.cover]
  enabled = true

  [params.imageProcessing.content]
  enabled = false
  
[[menu.main]]
identifier = "home"
name = "主页"
url = "/"
weight = -100

  [menu.main.params]
  newTab = false
  icon = "home"

[[menu.social]]
identifier = "Lofter"
name = "Lofter"
url = "https://springcecilia.lofter.com/"

  [menu.social.params]
  icon = "Lofter"

[[menu.social]]
identifier = "AO3"
name = "AO3（需魔法）"
url = "https://archiveofourown.org/users/Springcecilia/works"

  [menu.social.params]
  icon = "AO3"

[[menu.social]]
identifier = "email"
name = "提问箱（需魔法）"
url = "https://peing.net/zh-CN/91e8000a0af399"

  [menu.social.params]
  icon = "mail"

[[menu.social]]
identifier = "rss"
name = "rss订阅"
url = "https://springcecilia.blog/index.xml"

  [menu.social.params]
  icon = "rss"


[related]
includeNewer = true
threshold = 90
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 2
  
  [[related.indices]]
  name = "date"
  weight = 1

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 1

[markup.highlight]
noClasses = false


[outputFormats.ENCRYPT]
    mediatype = "text/html"
    baseName = "index"
    isPlainText = true
    notAlternative = true
    isHTML = true



